POST http://localhost:8080/api/atms
Content-Type: application/json

{
    "atmCode": "ATM-002",
    "district": "South Delhi",
    "area": "Saket Mall, Delhi",
    "latitude": 28.5245,
    "longitude": 77.2066
}

###
GET http://localhost:8080/api/atms